__chaostoolkit_fuzzdicover_root = '/tmp/chaostoolkit-fuzzdiscover/'
tmp_folder = __chaostoolkit_fuzzdicover_root+'tmp/'
source_file_backup_data_binary = '../../backup/pickled_source_file_backup_data.bin'
input_file_backup_data_binary = '../../backup/pickled_input_file_backup_data.bin'
fuzz_Input_data_location = __chaostoolkit_fuzzdicover_root+'output/'
experiment_file_destination = __chaostoolkit_fuzzdicover_root+'experiment/'