from chaostoolkitfuzzdiscover.chaostoolkitfuzzdiscover_steadystatehypothesis.filenames import chaostoolkit_fuzzdicover_root, backup_root, source_file_backup_data_binary, input_file_backup_data_binary
from chaostoolkitfuzzdiscover.chaostoolkitfuzzdiscover_steadystatehypothesis.filenames import fuzz_Input_data_location
tmp_folder = chaostoolkit_fuzzdicover_root + 'tmp/'
experiment_file_destination = chaostoolkit_fuzzdicover_root + 'experiment/'
internal_read_mock_file = chaostoolkit_fuzzdicover_root+"fuzzed_file.txt"