from chaostoolkitfuzzdiscover.chaostoolkitfuzzdiscover_steadystatehypothesis.filenames import chaostoolkit_fuzzdicover_root
from chaostoolkitfuzzdiscover.chaostoolkitfuzzdiscover_steadystatehypothesis.filenames import fuzz_Input_data_location
tmp_folder = chaostoolkit_fuzzdicover_root + 'tmp/'
backup_root = chaostoolkit_fuzzdicover_root + 'backup/'
source_file_backup_data_binary = backup_root+'pickled_source_file_backup_data.bin'
input_file_backup_data_binary = backup_root+'pickled_input_file_backup_data.bin'
experiment_file_destination = chaostoolkit_fuzzdicover_root + 'experiment/'
internal_read_mock_file = chaostoolkit_fuzzdicover_root+"fuzzed_file.txt"